planner/config/routes.rb
Planner::Application.routes.draw do
  
  resources :adults

  resources :families

  root :to => "trips#index"
  resources :addresses

  resources :address_catalogs

  resources :address_types
  
  resources :trip_states

  resources :trips

  resources :kids

end

planner/app/models/family.rb
class Family < ActiveRecord::Base
  belongs_to  :address
  has_and_belongs_to_many  :addresses
  has_many  :kids
  has_many  :adults
end

planner/app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  # GET /families
  # GET /families.json
  def index
    @families = Family.all
     
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @families.as_json(:include => [:address, :adults, :kids])}
    end
  end

  # GET /families/1
  # GET /families/1.json
  def show
    @family = Family.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @family }
    end
  end

  # GET /families/new
  # GET /families/new.json
  def new
    @family = Family.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @family }
    end
  end

  # GET /families/1/edit
  def edit
    @family = Family.find(params[:id])
  end

  # POST /families
  # POST /families.json
  def create
    @family = Family.new(params[:family])
    @address = Address.new 
    
   @address.name = params[:family][:last_name] + "'s Home"
   @address.address_type_id = AddressType.find(:first, :conditions => {:name=>'residency'}).id
   @address.address_catalog_id = AddressCatalog.find(:first, :conditions => {:name=>'other'}).id
   @address.address = params[:address]
    respond_to do |format|
      if addr = Address.find(:first, :conditions => {:address => @address.address})  
        @family.address_id = addr.id
      else 
        @address.save! 
        @family.address_id = @address.id
      end   
      if @family.save!
        format.html { redirect_to :action=>"edit", :id=>@family.id, :notice => 'Family was successfully created.' }
        format.json { render :json => @family, :status => :created, :location => @family }
      else
        format.html { render :action => "new" }
        format.json { render :json => @family.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /families/1
  # PUT /families/1.json
  def update
    @family = Family.find(params[:id])
    @address = Address.find(@family.address_id) 
    @address.address = params[:address]
    respond_to do |format|
      if @family.update_attributes(params[:family])
        @address.save    
        format.html { redirect_to @family, :notice => 'Family was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @family.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1
  # DELETE /families/1.json
  def destroy
    @family = Family.find(params[:id])
    @family.destroy

    respond_to do |format|
      format.html { redirect_to families_url }
      format.json { head :no_content }
    end
  end
end

planner/app/helpers/families_helper.rb
module FamiliesHelper
end

planner/app/views/families/_form.html.erb
<%= form_for(@family) do |f| %>
  <% if @family.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@family.errors.count, "error") %> prohibited this family from being saved:</h2>

      <ul>
      <% @family.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name%>
  </div>
    

  <div class="field">
    <%= f.label :address %> <br> 
    <%if @family.address_id.nil? %>
    <input size=50  type='text' name="address" value=""><br>
    <%else%>
    <input size=50  type='text' name="address" id=<%=@family.address_id%> value="<%=Address.find(@family.address_id).address.to_s%>"><br>
    <%end%>
  </div>

  
  <%if !@family.address_id.nil? %>
    <div class="field">
      <%= f.label :adults %> <br>
      <%if !@family.adults.empty? %>
      	<%@family.adults.each do |a| %>
          <%= link_to a.name, edit_adult_path(a.id) %> <br />
      	<%end%>         
      <%end%> 
      <%= link_to "Add a new adult", new_adult_path(:family_id=>@family.id, :seats=>3)%> <br />  
    </div>
    <div class="field">
      <%= f.label :kids %> <br>
      <%if !@family.kids.empty? %>
      	<%@family.kids.each do |a| %>
          <%= link_to a.name, edit_kid_path(a.id) %> <br />
      	<%end%>         
      <%end%> 
      <%= link_to "Add a new kid", new_kid_path(:family_id=>@family.id)%> <br />  
    </div>
  <%end%>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

planner/app/views/families/edit.html.erb
<h1>Editing family</h1>

<%= render 'form' %>

<%= link_to 'Show', @family %> |
<%= link_to 'Back', families_path %>

planner/app/views/families/index.html.erb
<h1>Listing families</h1>

<table border = 1>
  <tr>
    <th>Last Name</th>
    <th>Address</th>
    <th>Adults</th>
    <th>Kids</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @families.each do |family| %>
  <tr>
    <td><%= family.last_name %></td>
    <td><%= family.address.address %></td>

    <td><% adult_names = []
           family.adults.each do |adult|
            adult_names << adult.name
           end %>
         <%=adult_names.join(", ")%></td>  
    <td><% kid_names = []
           family.kids.each do |kid|
            kid_names << kid.name
           end %>
         <%=kid_names.join(",") %></td>  
    <td><%= link_to 'Show', family %></td>
    <td><%= link_to 'Edit', edit_family_path(family) %></td>
    <td><%= link_to 'Destroy', family, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Family', new_family_path %>

planner/app/views/families/new.html.erb
<h1>New family</h1>

<%= render 'form' %>

<%= link_to 'Back', families_path %>

planner/app/views/families/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Last Name:</b>
  <%= @family.last_name %>
</p>
<p>
  <b>Address:</b>
  <%= @family.address.address %>
</p>
<p>
  <b>Adults:</b>
  <%@family.adults.each do |adult| %>
  <div>
    <dd><b>Name: </b>
    <%=adult.name %><br />
    <b>Can be a Driver? </b>
    <%=adult.drive%><br />
    <b>Driver License:</b>
    <%=adult.driver_license%> <br />
    <b>Avaliable seats: </b>
    <%=adult.seats%><br />
    <b>Email: </b>
    <%=adult.email%><br />
  </div> <br />
  <%end%>
</p>
<p>
  <b>Kids:</b>
  <%@family.kids.each do |kid| %>
  <div><dd>
    <b>Name: </b>
    <%=kid.name %><br />
    <b>Birthday </b>
    <%=kid.birthday.to_s%><br />
    <b>school</b>
    <%=kid.school.name + '|' + kid.school.address%> <br />
  </div> <br />
  <%end%>
</p>


<%= link_to 'Edit', edit_family_path(@family) %> |
<%= link_to 'Back', families_path %>