planner/config/routes.rb
Planner::Application.routes.draw do
  
  resources :adults

  resources :families

  root :to => "trips#index"
  resources :addresses

  resources :address_catalogs

  resources :address_types
  
  resources :trip_states

  resources :trips

  resources :kids

end

planner/app/models/adult.rb
class Adult < ActiveRecord::Base
  belongs_to :family
end

planner/app/controllers/adults_controller.rb
class AdultsController < ApplicationController
  # GET /adults
  # GET /adults.json
  def index
    @adults = Adult.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @adults }
    end
  end

  # GET /adults/1
  # GET /adults/1.json
  def show
    @adult = Adult.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @adult }
    end
  end

  # GET /adults/new
  # GET /adults/new.json
  def new
    @adult = Adult.new
    @adult.family_id = params[:family_id] if params[:family_id]
    @adult.seats = params[:seats] if params[:seats]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @adult }
    end
  end

  # GET /adults/1/edit
  def edit
    @adult = Adult.find(params[:id])
  end

  # POST /adults
  # POST /adults.json
  def create
    @adult = Adult.new(params[:adult])

    respond_to do |format|
      if @adult.save
        format.html { redirect_to @adult, :notice => 'Adult was successfully created.' }
        format.json { render :json => @adult, :status => :created, :location => @adult }
      else
        format.html { render :action => "new" }
        format.json { render :json => @adult.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /adults/1
  # PUT /adults/1.json
  def update
    @adult = Adult.find(params[:id])

    respond_to do |format|
      if @adult.update_attributes(params[:adult])
        format.html { redirect_to @adult, :notice => 'Adult was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @adult.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /adults/1
  # DELETE /adults/1.json
  def destroy
    @adult = Adult.find(params[:id])
    @adult.destroy

    respond_to do |format|
      format.html { redirect_to adults_url }
      format.json { head :no_content }
    end
  end
end

planner/app/helpers/adults_helper.rb
module AdultsHelper
end

planner/app/views/adults/_form.html.erb
<%= form_for(@adult) do |f| %>
  <% if @adult.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adult.errors.count, "error") %> prohibited this adult from being saved:</h2>

      <ul>
      <% @adult.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :family_id %><br />
    <%= f.select :family_id, Family.all.collect{|u|[u.last_name, u.id]} %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :drive %><br />
    <%= f.check_box :drive %>
  </div>
  <div class="field">
    <%= f.label :driver_license %><br />
    <%= f.text_field :driver_license %>
  </div>
  <div class="field">
    <%= f.label :seats %><br />
    <%= f.number_field :seats %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

planner/app/views/adults/edit.html.erb
<h1>Editing adult</h1>

<%= render 'form' %>

<%= link_to 'Show', @adult %> |
<%= link_to 'Back to Adult list', adults_path %>
<%= link_to 'Back to Edit Family', edit_family_path(@adult.family_id) %>

planner/app/views/adults/index.html.erb
<h1>Listing adults</h1>

<table>
  <tr>
    <th>Family</th>
    <th>Name</th>
    <th>Email</th>
    <th>Drive</th>
    <th>Driver license</th>
    <th>Seats</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @adults.each do |adult| %>
  <tr>
    <td><%= adult.family.last_name %></td>
    <td><%= adult.name %></td>
    <td><%= adult.email %></td>
    <td><%= adult.drive %></td>
    <td><%= adult.driver_license %></td>
    <td><%= adult.seats %></td>
    <td><%= link_to 'Show', adult %></td>
    <td><%= link_to 'Edit', edit_adult_path(adult) %></td>
    <td><%= link_to 'Destroy', adult, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Adult', new_adult_path %>

planner/app/views/adults/new.html.erb
<h1>New adult</h1>

<%= render 'form' %>

<%= link_to 'Back to Adults List', adults_path %>
<%= link_to 'Back to Edit Family', edit_family_path(params[:family_id]) %>

planner/app/views/adults/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Family:</b>
  <%= Family.find(@adult.family_id).last_name %>
</p>

<p>
  <b>Name:</b>
  <%= @adult.name %>
</p>

<p>
  <b>Email:</b>
  <%= @adult.email %>
</p>

<p>
  <b>Drive:</b>
  <%= @adult.drive %>
</p>

<p>
  <b>Driver license:</b>
  <%= @adult.driver_license %>
</p>

<p>
  <b>Seats:</b>
  <%= @adult.seats %>
</p>


<%= link_to 'Edit', edit_adult_path(@adult) %> |
<%= link_to 'Back to Adult list', adults_path %> |
<%= link_to 'Back to Edit Family', edit_family_path(@adult.family_id) %>