planner/config/routes.rb
Planner::Application.routes.draw do
  
  resources :adults

  resources :families

  root :to => "trips#index"
  resources :addresses

  resources :address_catalogs

  resources :address_types
  
  resources :trip_states

  resources :trips

  resources :kids

end

planner/app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :start, :class_name => 'Address'
  belongs_to :destination, :class_name => 'Address'
  belongs_to :kid
  belongs_to :trip_state, :validate=>true
  validates_associated :trip_state
  validates_presence_of :trip_state, :message => "invalid!"
  default_scope :order => 'id'
end

planner/app/controllers/trips_controller.rb
class TripsController < ApplicationController
  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @trips }
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @trip }
    end
  end

  # GET /trips/new
  # GET /trips/new.json
  def new
    @trip = Trip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @trip }
    end
  end

  # GET /trips/1/edit
  def edit
    @trip = Trip.find(params[:id])
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(params[:trip])
    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, :notice => 'Trip was successfully created.' }
        format.json { render :json => @trip, :status => :created, :location => @trip }
      else
        format.html { render :action => "new" }
        format.json { render :json => @trip.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /trips/1
  # PUT /trips/1.json
  def update
    @trip = Trip.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to @trip, :notice => 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @trip.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end
end

planner/app/helpers/trips_helper.rb
module TripsHelper
end

planner/app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :trip_id, "TRIP ID" %><br />
    <%= f.text_field :id, :readonly=>true %>
  </div>
  <div class="field">
    <%= f.label :kid_name %>
    <%= link_to "Add a new kid", new_kid_path, :target => "_blank" %><br />
    <%= select("trip", :kid_id, Kid.all.collect {|s| [s.name, s.id]}) %>
  </div>
  <div class="field">
    <%= f.label :start_address %>
    <%= link_to "Add a new address", new_address_path, :target => "_blank" %><br />
    <%= f.select :start_id, Address.all.collect {|s| [s.name, s.id]} %>
  </div>
  <div class="field">
    <%= f.label :destination %>
    <%= link_to "Add a new address", new_address_path, :target => "_blank" %><br />
    <%= f.select :destination_id, Address.all.collect {|s| [s.name, s.id]} %>
  </div>
  <div class="field">
    <%= f.label :arrive_time %><br />
    <%= f.datetime_select :arrive_time %>
  </div>
  <div class="field">
    <%= f.label :extra_seats %><br />
    <%= f.select :extra_seats, 1..5 %>
  </div>
  <div class="field">
    <%= f.label :matched %><br />
    <%= select("trip", :matched, [['No', 0], ['Yes', 1]]) %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= select("trip", :trip_state_id, TripState.all.collect {|s| [s.state, s.id]}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

planner/app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

planner/app/views/trips/index.html.erb
<h1>Listing trips</h1>

<table>
  <tr>
    <th>Trip ID</th>
    <th>Kid Name</th>
    <th>State Address</th>
    <th>Destination</th>
    <th>Arrive Time</th>
    <th>Extra Seats</th>
    <th>Matched</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trips.each do |trip| %>
  <tr>
    <td><%= trip.id %></td>
    <td><%= trip.kid.name %></td>
    <td><%= trip.start.name %></td>
    <td><%= trip.destination.name %></td>
    <td><%= trip.arrive_time %></td>
    <td><%= trip.extra_seats %></td>
    <td><%= trip.matched %></td>
    <td><%= trip.trip_state.state %></td>
    <td><%= link_to 'Show', trip %></td>
    <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
    <td><%= link_to 'Destroy', trip, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Trip', new_trip_path %>
<%= link_to 'Kids', kids_path %>
<%= link_to 'Addresses', addresses_path %>

planner/app/views/trips/new.html.erb
<h1>New trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

planner/app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Trip ID:</b>
  <%= @trip.id %>
</p>
<p>
  <b>Kid Name:</b>
  <%= @trip.kid.name %>
</p>
<p>
  <b>Start Address:</b>
  <%= @trip.start.name %> |
  <%= @trip.start.address %>
  
</p>
<p>
  <b>Destination:</b>
  <%= @trip.destination.name %> |
  <%= @trip.destination.address %>
</p>
<p>
  <b>Arrive Time:</b>
  <%= @trip.arrive_time %>
</p>
<p>
  <b>Extra seats:</b>
  <%= @trip.extra_seats %>
</p>

<p>
  <b>Matched:</b>
  <%= @trip.matched %>
</p>
<p>
  <b>Status:</b>
  <%= @trip.trip_state.state %>
</p>


<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>